-- Carrega os módulos
require('user.options')
require('user.plugins')
require('user.lsp')
require('user.cmp')
require('user.nvimtree')
require('user.keymaps')
require('user.autosaveTimer')
require('user.lualineConfig')
require('user.theme')
